### ISSUE TITLE
Non-stationary kernel implementations

### ISSUE THREAD

**Issue by patel-zeel** [wesselb/mlkernels#1]
I am working on a project where I am planning to implement some useful generalized non-stationary kernel papers like [this one](https://www.jstor.org/stable/4140539?seq=1#metadata_info_tab_contents). I saw Stheno a few days back and thought of using it as a potential platform for our implementations. Would you be interested in full-time collaborating with us or maybe helping us occasionally with the project?

**Comment by wesselb** [comment]
Hey @patel-zeel! I've sent you an email.
