### ISSUE TITLE
Decaying kernel not positive definite in ND

### ISSUE THREAD

**Issue by Gattocrucco** [wesselb/mlkernels#3]
I was trying the decaying kernel (not with mlkernel itself because I'm lazy), and it results not pos def when used in more than 1 dimensions:

```python
import numpy as np
from matplotlib import pyplot as plt

nd = 2
alpha = 1
beta = np.ones(nd)
nx = 5

def kernel(x, y, alpha, beta):
    bn2 = np.sum(beta ** 2)
    xyb = x + y + beta
    xybn2 = np.sum(xyb ** 2, axis=-1)
    return (bn2 / xybn2) ** (alpha / 2)

gen = np.random.default_rng(202206241555)
x = gen.uniform(0, 5, (nx, nd))
c = kernel(x[None, :, :], x[:, None, :], alpha, beta)
w = np.linalg.eigvalsh(c)
error = len(c) * np.finfo(float).eps * np.max(w)
if np.min(w) < -error:
    print('NOT POSITIVE!')

fig, ax = plt.subplots(num='decaying', clear=True)

ax.plot(w)

fig.show()
```

<img width="568" alt="image" src="https://user-images.githubusercontent.com/9684110/175552371-ec9a8126-7887-4a41-832d-fec71fadb596.png">

**Comment by wesselb** [comment]
Ouch... that's very messy. 😬 I'm finding the same. Let me see if I can figure out what the right multivariate version is. Thanks for raising this!

**Comment by Gattocrucco** [comment]
Did you manage to make it work? What was the solution?

**Comment by wesselb** [comment]
Hey @Gattocrucco! I believe the original derivation goes through if you simply replace `t` with `norm(t)` for any `norm`, which I think makes sense. I chose the one-norm in the code. The changes needed to make it work again were super minimal. 😅 Sorry, by the way, for getting back to this. The issue had temporarily gone off my radar.

**Comment by Gattocrucco** [comment]
Ok, thanks.

> Sorry, by the way, for getting back to this. The issue had temporarily gone off my radar.

No problem, I just asked for curiosity when I received the github notification.

Yeah I think the 1-norm makes sense since there's a $e^{-\lambda t}$.
